### ISSUE TITLE
Function ambiguity

### ISSUE THREAD

**Issue by AndriiVaskiv** [andrewDubyk/E-learning-Interfaces-UnitTesting-Task1#8]
https://github.com/andrewDubyk/E-learning-Interfaces-UnitTesting-Task1/blob/ae07a3854b32462da6195be5781c470ebea1c37a/E-learning_task_4_interfaces/Utils.cs#L17-L24

For input (3, 0) and (0, 3) function returns different values.

**Comment by andrewDubyk** [comment]
Fixed . [code](https://github.com/andrewDubyk/E-learning-Interfaces-UnitTesting-Task1/blob/807f0ba2a8579bd73d636f2145ef5a3cce392798/E-learning_task_4_interfaces/Utils.cs#L17-L29)
