### ISSUE TITLE
DivideByZero

### ISSUE THREAD

**Issue by AndriiVaskiv** [andrewDubyk/E-learning-Interfaces-UnitTesting-Task1#9]
https://github.com/andrewDubyk/E-learning-Interfaces-UnitTesting-Task1/blob/ae07a3854b32462da6195be5781c470ebea1c37a/E-learning_task_4_interfaces/Task.cs#L70-L76

There is a possibility to divide by zero.

**Comment by andrewDubyk** [comment]
if it is class IntegerNumber divide function is 
```c#
        public void Divide(int num)
        {
            if (num == 0)
            {
                throw new DivideByZeroException();
            }
            this.Number /= num;
        }
```
and exception will be thrown.

If it is class RationalNumber this fucntion is 
```c#
        public void Divide(int num)
        {
            this.Denominator *= num;
        }
```
and exception will be thrown in [Denominator proprties ](https://github.com/andrewDubyk/E-learning-Interfaces-UnitTesting-Task1/blob/master/E-learning_task_4_interfaces/Classes/RationalNumber.cs#L17-L24)
